# Generated by Django 5.0.6 on 2024-07-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_caso_contrato_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_abogado', to='account.caso'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.caso'),
        ),
    ]
